<a href="https://colab.research.google.com/github/rmace001/Github-workflow-testing/blob/master/CS242HW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import math
import numpy as np

# Exercise A

In [3]:
####################################################
# Homework for CS242
# Author: Rogelio Macedo
# UCR Department of Computer Science and Engineering
# CS 242 Information Retrieval
####################################################

# BM25 
# Using assumptions from class
# Assuming univeristy and University is counted equally

N = 1000
r_i = 0
R = 0
k1 = 1.2
k2 = 100
b = .75
dl_adl = 1
K = k1*(1-b) + b * dl_adl

def scoring(f_i, qf_i, n_i):

  inner = \
  ((r_i + .5)/(R - r_i + .5)) / ((n_i - r_i + .5)/(N - n_i - R + r_i + .5))
  
  inner = math.log(inner, 2)
  inner *= (((k1 + 1)*f_i)/(K + f_i)) * (((k2 + 1) * qf_i) / (k2 + qf_i))
  return inner


# Q1: university Riverside
s = 0
nis = [200, 100]
f1 = [4, 1]
qf = [1, 1]
for i in range(len(f1)):
  s += scoring(f_i=f1[i], qf_i=qf[i], n_i=nis[i])
print('Q1 Score: {0}'.format(s))

# Q2: diverse university
s = 0
nis = [150, 200]
f2 = [1, 4]
qf = [1, 1]
for i in range(len(f2)):
  s += scoring(f_i=f2[i], qf_i=qf[i], n_i=nis[i])
print('Q2 Score: {0}'.format(s))


Q1 Score: 6.875450747449154
Q2 Score: 6.161810427053025


In [4]:
# Unigram LM with JM Smoothing
# Only take the product and not the log of the product

lamb = 0.1
D = 40
C = 1000

def pr(fqd, fqc):
  return (1-lamb) * (fqd/D) + lamb * (fqc/C)

# Q1: university Riverside
fQ = [1, 1]
fC = [200, 100]
p = 1

for i in range(len(fQ)):
  p *= pr(fqd=fQ[i], fqc=fC[i])
print('Q1 Score: {0}'.format(p))

# Q2: diverse university
fQ = [1, 1]
fC = [150, 200]
p = 1

for i in range(len(fQ)):
  p *= pr(fqd=fQ[i], fqc=fC[i])
print('Q2 Score: {0}'.format(p))

Q1 Score: 0.0013812500000000003
Q2 Score: 0.0015937500000000005


# Exercise B

In [5]:
# PageRank

# numpy things
float_formatter = "{:.2f}".format
np.set_printoptions(formatter={'float_kind':float_formatter})
# Damping Factor
d = .85

# Number of pages
N = 5

# Convergence Threshold
threshold = .0001
print("Constants defined.")
# PageRank
def pageRank(matrix, Y, B):
  return np.dot(d * matrix, Y) + (1-d)*B


# Outgoing links
out = {i: list() for i in range(1, N+1)}

out[1] = [2]
out[2] = [3, 5]
out[3] = [1]
out[4] = [5]
out[5] = [5]

print('Outgoing links have been set.')
print(out)

M = np.zeros((N, N))
yfinal = np.array([1, 1, 1, 1, 1])
yfinal = yfinal.T

for i in range(1, N+1):
  for j in out[i]:
    M[j-1, i-1] = 1/len(out[i])

b = np.full((5,), 1/5)

print("Matrix M, and vectors Y and B have been initialized.\n")
print('M: ')
print(M)
print('Y: ', yfinal)
print('B: ', b)

print('\nRunning iterations...')
iterations = 0
diff = abs(yfinal - np.zeros((5,)))
check = (diff < threshold).all()
while(not check):
  print('Iteration {0}'.format(iterations))
  ytemp = pageRank(matrix=M, Y=yfinal, B=b)
  diff = abs(yfinal - ytemp)
  check = (diff < threshold).all()
  yfinal = ytemp
  print('Current Y: ', yfinal)
  print('Pagewise PR difference from last iteration: ', diff)
  iterations += 1
  print('\n')

print('Iterations done! Number of iterations with threshold of 0.0001: {0}'
  .format(iterations))

Constants defined.
Outgoing links have been set.
{1: [2], 2: [3, 5], 3: [1], 4: [5], 5: [5]}
Matrix M, and vectors Y and B have been initialized.

M: 
[[0.00 0.00 1.00 0.00 0.00]
 [1.00 0.00 0.00 0.00 0.00]
 [0.00 0.50 0.00 0.00 0.00]
 [0.00 0.00 0.00 0.00 0.00]
 [0.00 0.50 0.00 1.00 1.00]]
Y:  [1 1 1 1 1]
B:  [0.20 0.20 0.20 0.20 0.20]

Running iterations...
Iteration 0
Current Y:  [0.88 0.88 0.46 0.03 2.15]
Pagewise PR difference from last iteration:  [0.12 0.12 0.54 0.97 1.15]


Iteration 1
Current Y:  [0.42 0.78 0.40 0.03 2.26]
Pagewise PR difference from last iteration:  [0.46 0.10 0.05 0.00 0.11]


Iteration 2
Current Y:  [0.37 0.38 0.36 0.03 2.31]
Pagewise PR difference from last iteration:  [0.04 0.39 0.04 0.00 0.05]


Iteration 3
Current Y:  [0.34 0.35 0.19 0.03 2.18]
Pagewise PR difference from last iteration:  [0.04 0.04 0.17 0.00 0.13]


Iteration 4
Current Y:  [0.19 0.32 0.18 0.03 2.06]
Pagewise PR difference from last iteration:  [0.14 0.03 0.02 0.00 0.12]


Iteration 5
C

# Exercise C

# Map 
## Input
Collection of input documents

## Emits:
Key value pair for every document that contains the `Pair`:
  - Key: `Pair(keyword1, keyword2)`
  - Value: 1

## Combiner
Groups together a list for each unique `Pair(keyword1, keyword2)`


# Reduce
## Input
Key value pair: 
  - Key: `Pair(keyword1, keyword2)`
  - Value: List of all values for the particular `Pair(keyword1, keyword2)`

## Emits
```
If len(list) > 1000
  emit(Pair(keyword1, keyword2), len(list))
```

# Exercise D

In [6]:
results = [0, 0, 1, 1, 1, 0, 1, 1, 0]
n = 5

def Precision(A, B):
  precision = len(set.intersection(set(A), set(B))) / len(B)
  return precision

def Recall(A, B):
  recall = len(set.intersection(A, B)) / len(A)
  return recall

def PrecisionAtN(n, vals):
  cnt = 0
  for i in range(n):
    if vals[i] == 1:
      cnt += 1
  return cnt/n

def RecallAtN(n, vals, relC):
  cnt = 0
  for i in range(n):
    if vals[i] == 1:
      cnt += 1
  return cnt/relC

print('Precision at 5: {0}'.format(PrecisionAtN(n, results[:n])))
print('Recall at 5: {0}'.format(RecallAtN(n, results[:n], 6)))

Precision at 5: 0.6
Recall at 5: 0.5


In [7]:
# f Score

beta = 0.5

def FScore(R, P):
  return (2 * R * P) / (R + P)

def FScore2(R, P):
  return (beta**2 + 1) * R * P / (R + (beta**2) * P)

print('F-score at 5: {0}'.format(
    FScore2(
        RecallAtN(n, results[:n], 6),
        PrecisionAtN(n, results[:n])
    )
  )
)

F-score at 5: 0.5769230769230769


In [8]:
# Avg Precision
rels = results
precisions = [PrecisionAtN(i+1, rels[:i+1]) for i in range(len(results))]
nRel = 6
sizes = []

for i in range(len(results)):
  if results[i] == 1:
    sizes.append(i+1)

s = 0

for i in range(len(sizes)):
  s += precisions[sizes[i]]

print('Average precision at 5: {0}'.format(s/nRel))

Average precision at 5: 0.46342592592592596


In [9]:
# DCG
s = 0
at = 5
rels = results[:at]
i = 1

for r_i in rels:
  s += ((2**r_i) - 1) / math.log(1+i)
  i += 1

print('DCG at 5: {0}'.format(s))

DCG at 5: 1.9007930815553407


2. High precision is good for situations like mobile browsing/searching. High recall is good for search in medical databases of experiements/documents/papers/scientific research/etc.